/**
 * Copyright (C) 2003-2007 eXo Platform SAS.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see<http://www.gnu.org/licenses/>.
 */

package org.exoplatform.services.ws.impl.xfire.transport.http;

import java.io.IOException;
import java.util.Iterator;
import org.apache.commons.logging.Log;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.codehaus.xfire.XFire;
import org.codehaus.xfire.XFireFactory;
import org.codehaus.xfire.transport.Transport;
import org.codehaus.xfire.transport.http.XFireServletController;

import org.exoplatform.services.log.ExoLogger;

/**
 * @author <a href="mailto:andrew00x@gmail.com">Andrey Parfonov</a>
 * @version $Id: $
 */
public class XFireServlet extends HttpServlet {

  /**
   * Generated by Eclipse.
   */
  private static final long serialVersionUID = -5378038765850618608L;
  
  /**
   * Session attribute name for XFire. 
   */
  public static final String XFIRE_INSTANCE = "xfire.instance";
  
  /**
   * XFire engine.
   */
  protected XFire xfire;
  
  /**
   * Servlet controller.
   */
  protected XFireServletController controller;

  /**
   * Logger.
   */
  private static final Log LOG = ExoLogger.getLogger("ws.soap.XFireServlet");

  /**
   * {@inheritDoc}
   */
  @Override
  public void init() throws ServletException {
    try {
      super.init();
      xfire = createXFire();
      controller = createController();

      if (LOG.isDebugEnabled()) {
        LOG.debug(xfire);
        LOG.debug(controller);
      }
      
    } catch (Exception e) {
      LOG.error("Error initializing XFireServlet.", e);
      throw new ServletException("Error initializing XFireServlet.", e);
    }
  }

  /**
   * {@inheritDoc}
   */
  @Override
  protected void doGet(HttpServletRequest request, HttpServletResponse response)
      throws ServletException, IOException {
    if (LOG.isDebugEnabled())
      LOG.debug("doGet called");
    controller.doService(request, response);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  protected void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException,
      IOException {
    if (LOG.isDebugEnabled())
      LOG.debug("doPost called");
    controller.doService(req, res);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public void destroy() {
    if (LOG.isDebugEnabled())
      LOG.debug("Destroying Servlet");
    // Ensure all transports are closed
    for (Iterator < ? > iterator =
      xfire.getTransportManager().getTransports().iterator(); iterator.hasNext();) {
      
      Transport transport = (Transport) iterator.next();
      transport.dispose();
    }
    super.destroy();
  }

  /**
   * Create new instance of XFire.
   * @return XFire instance.
   * @throws ServletException if something going wrong.
   */
  private XFire createXFire() throws ServletException {
    try {
      if (getServletContext().getAttribute(XFIRE_INSTANCE) != null) {
        return (XFire) getServletContext().getAttribute(XFIRE_INSTANCE);
      }
      XFireFactory factory = XFireFactory.newInstance();
      return factory.getXFire();
    } catch (Exception e) {
      throw new ServletException("Couldn't start XFire.", e);
    }
  }

  /**
   * Create new instance of XFireServletController.
   * @return XfireServletController instance.
   */
  private XFireServletController createController() {
    return new XFireServletController(xfire, getServletContext());
  }
}
