package org.exoplatform.services.ws.soap.jsr181;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.2
 * Wed Oct 22 10:22:32 EEST 2008
 * Generated source version: 2.1.2
 * 
 */
 
@WebService(targetNamespace = "http://jsr181.soap.ws.services.exoplatform.org/", name = "TicketOrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface TicketOrderService {

    @ResponseWrapper(localName = "getTicketResponse", targetNamespace = "http://jsr181.soap.ws.services.exoplatform.org/", className = "org.exoplatform.services.ws.soap.jsr181.GetTicketResponse")
    @RequestWrapper(localName = "getTicket", targetNamespace = "http://jsr181.soap.ws.services.exoplatform.org/", className = "org.exoplatform.services.ws.soap.jsr181.GetTicket")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public java.lang.String getTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @ResponseWrapper(localName = "confirmationResponse", targetNamespace = "http://jsr181.soap.ws.services.exoplatform.org/", className = "org.exoplatform.services.ws.soap.jsr181.ConfirmationResponse")
    @RequestWrapper(localName = "confirmation", targetNamespace = "http://jsr181.soap.ws.services.exoplatform.org/", className = "org.exoplatform.services.ws.soap.jsr181.Confirmation")
    @WebMethod
    public void confirmation(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0
    );
}
