/**
 * Copyright (C) 2003-2008 eXo Platform SAS.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see<http://www.gnu.org/licenses/>.
 */

package org.exoplatform.services.security.sso;

/**
 * @author <a href="mailto:andrew00x@gmail.com">Andrey Parfonov</a>
 * @version $Id: $
 */
public class SSOAuthenticationException extends Exception {
  
  /**
   * Generated by Eclipse.
   */
  private static final long serialVersionUID = 1674941502229201474L;

  /**
   * @param message the message.
   * @param cause the cause.
   */
  public SSOAuthenticationException(final String message,
      final Throwable cause) {
    super(message, cause);
  }

  /**
   * @param message the message.
   */
  public SSOAuthenticationException(final String message) {
    super(message);
  }

  /**
   * @param cause the cause.
   */
  public SSOAuthenticationException(final Throwable cause) {
    super(cause);
  }
}

