package org.exoplatform.services.rest.util;

import java.util.ArrayList;
import java.util.List;

import javax.ws.rs.core.MediaType;

import org.exoplatform.services.rest.impl.provider.ProviderFactory;
import org.exoplatform.services.rest.provider.EntityProvider;

/**
 * Keeps sorted instances of ProviderFactory.
 * 
 * @see EntityProvider
 * @see MediaTypeMap
 */
public class EntityProviderMap extends MediaTypeMap<List<ProviderFactory>> implements
    NotNullValueMultivaluedMap<MediaType, ProviderFactory> {

  /**
   * Generated by Eclipse.
   */
  private static final long serialVersionUID = 7082102018450744774L;

  /**
   * Get {@link List} with specified key. If it does not exist new one be
   * created.
   * 
   * @param mediaType MediaType
   * @return List of ProviderFactory if no value mapped to the specified key
   *         then empty list will be returned instead null
   */
  public List<ProviderFactory> getList(MediaType mediaType) {
    List<ProviderFactory> l = get(mediaType);
    if (l == null) {
      l = new ArrayList<ProviderFactory>();
      put(mediaType, l);
    }
    return l;
  }

}
