package org.exoplatform.services.rest.util;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import org.exoplatform.services.rest.RequestFilter;
import org.exoplatform.services.rest.ResponseFilter;
import org.exoplatform.services.rest.impl.uri.UriPattern;

/**
 * @param <V> {@link RequestFilter} or {@link ResponseFilter}
 */
public class FilterMap<V> extends HashMap<UriPattern, List<V>> implements
    NotNullValueMultivaluedMap<UriPattern, V> {

  /**
   * Generated by Eclipse.
   */
  private static final long serialVersionUID = 8248982446381545144L;

  /**
   * @param uriPattern the key
   * @return List of Object mapped to specified <tt>uriPattern</tt>. Method
   *         never return null, empty List instead.
   */
  public List<V> getList(UriPattern uriPattern) {
    List<V> l = get(uriPattern);
    if (l == null) {
      l = new ArrayList<V>();
      put(uriPattern, l);
    }
    return l;
  }

}